import Head from "next/head";
import {
  Flex,
  Text,
  Center,
  Heading,
  Button,
  Stack,
  Box,
  Modal,
  ModalBody,
  ModalFooter,
  FormControl,
  ModalContent,
  ModalCloseButton,
  Input,
  Textarea,
  ModalOverlay,
  ModalHeader,
  useDisclosure,
  FormLabel,
} from "@chakra-ui/react";
import bgImage from "../assets/cor2.gif";
import { FiPackage } from "react-icons/fi";
import { GiBoxUnpacking, GiPackedPlanks, GiJetpack } from "react-icons/gi";
import { useState } from "react";

export default function Home() {
  const { isOpen, onOpen, onClose } = useDisclosure();
  const [open, setOpen] = useState(false);
  const [planType, setPlanType] = useState("");
  const openFirst = (e) => {
    open === false ? setOpen(true) : (open = false);
    setPlanType(e.target.value);
  };

  const closeModal = () => {
    setOpen(false);
  };
  return (
    <div>
      <Head>
        <title>Fortune World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        background={`linear-gradient(rgba(0, 0, 0, 0.521), rgba(0, 0, 0, 0.521)), url(${bgImage.src})`}
        height="60vh"
        backgroundSize="cover"
        backgroundRepeat="no-repeat"
        backgroundPosition="center"
        justifyContent="center"
        flexDirection="column"
        position="relative"
      >
        <Center marginBottom="4rem">
          <Heading
            color="white"
            fontSize={["18px", "18px", "20px", "25px"]}
            textTransform="uppercase"
          >
            Corporate Scheme
          </Heading>
        </Center>
        <Stack
          // width="70%"
          padding="20px"
          color="white"
          backgroundColor="#2a69ac2d"
          position="absolute"
          bottom="0"
        >
          <Heading fontSize="18px">Fortune World General Trading</Heading>
          <Text
            fontSize={["12px", "12px", "15px", "15px"]}
            width={["100%", "100%", "90%", "70%"]}
          >
            Dubai renown business for dealing branded perfumes, jewelries, wears
            and delivery services since the last 20 years in business in the
            vicinity of Al Dagaya, Deira Dubai and reputed name within
            suppliers,Wholoesales and Exporters of international branded
            perfumes sales.
          </Text>
        </Stack>
      </Flex>
      <Flex
        margin="2rem 0"
        justifyContent="space-between"
        padding="30px"
        flexWrap="wrap"
      >
        <Center w="100%" flexDirection="column" marginBottom="2rem">
          <Heading
            fontSize={["15px", "20px", "25px", "25px"]}
            textTransform="uppercase"
            color="#153e75"
            marginBottom="1rem"
          >
            Classes of Corporate Scheme
          </Heading>
          <Text
            fontSize="15px"
            width={["100%", "100%", "70%", ""]}
            color="#153e75"
          >
            We offer a way good competitive price on all our new international
            branded perfume product sales. We welcome our potential prospective
            customers, partners, wholesalers, retailers and exporters highly
            applaud and belief on profitable and mutual beneficial business
            relationships.
          </Text>
        </Center>
        <Box
          width={["100%", "100%", "45%", "20%"]}
          bg="#153e75"
          padding="30px"
          borderRadius="10px"
          color="#ffff"
          margin="1rem 0"
        >
          <Stack
            position="relative"
            height={["35vh", "35vh", "22vh", "35vh"]}
            width="100%" 
          >
            <Center>
              <FiPackage fontSize="48px" />
            </Center>
            <Heading fontSize="15px" textAlign="center" my="1.4rem !important">
              Starter Purchase Package ($500-$900)
            </Heading>
            <Text textAlign="center" fontSize="14px">
              Free delivery worldwide
            </Text>
            <Button
              bg="#ffff"
              color="#153e75"
              position="absolute"
              bottom="0"
              right="2px"
              left="2px"
              margin="0 auto !important"
              value="Starter Purchase Package ($500-$900)"
              onClick={openFirst}
            >
              Purchase Plan
            </Button>
          </Stack>
        </Box>

        <Box
          width={["100%", "100%", "45%", "20%"]}
          bg="#153e75"
          padding="30px"
          borderRadius="10px"
          color="#ffff"
          margin="1rem 0"
        >
          <Stack
            position="relative"
            height={["35vh", "35vh", "22vh", "35vh"]}
            width="100%"
          >
            <Center>
              <GiBoxUnpacking fontSize="48px" />
            </Center>
            <Heading fontSize="15px" textAlign="center" my="1.4rem !important">
              Medium Purchase Package ($1000-$1500)
            </Heading>
            <Text textAlign="center" fontSize="14px">
              30% discount in purchase
            </Text>
            <Button
              bg="#ffff"
              color="#153e75"
              position="absolute"
              bottom="0"
              right="2px"
              left="2px"
              margin="0 auto !important"
              value="Medium Purchase Package ($1000-$1500)"
              onClick={openFirst}
            >
              Purchase Plan
            </Button>
          </Stack>
        </Box>
        <Box
          width={["100%", "100%", "45%", "20%"]}
          bg="#153e75"
          padding="30px"
          borderRadius="10px"
          color="#ffff"
          margin="1rem 0"
        >
          <Stack
            position="relative"
            height={["35vh", "35vh", "22vh", "35vh"]}
            width="100%"
          >
            <Center>
              <GiPackedPlanks fontSize="48px" />
            </Center>
            <Heading fontSize="15px" textAlign="center" my="1.4rem !important">
              Senior Purchase Package ($1600-$2000)
            </Heading>
            <Text textAlign="center" fontSize="14px">
              Free delivery + 20% discount in purchase
            </Text>
            <Button
              bg="#ffff"
              color="#153e75"
              position="absolute"
              bottom="0"
              right="2px"
              left="2px"
              margin="0 auto !important"
              value="Senior Purchase Package ($1600-$2000)"
              onClick={openFirst}
            >
              Purchase Plan
            </Button>
          </Stack>
        </Box>
        <Box
          width={["100%", "100%", "45%", "20%"]}
          bg="#153e75"
          padding="30px"
          borderRadius="10px"
          color="#ffff"
          margin="1rem 0"
        >
          <Stack
            position="relative"
            height={["35vh", "35vh", "22vh", "35vh"]}
            width="100%"
          >
            <Center>
              <GiJetpack fontSize="48px" />
            </Center>
            <Heading fontSize="15px" textAlign="center" my="1.4rem !important">
              Wholesale Purchase Package ($5000-$50000)
            </Heading>
            <Text textAlign="center" fontSize="14px" marginBottom="2rem">
              Free delivery and $550 free goods
            </Text>
            <Button
              bg="#ffff"
              color="#153e75"
              position="absolute"
              bottom="0"
              right="2px"
              left="2px"
              margin="0 auto !important"
              value="Wholesale Purchase Package ($5000-$50000)"
              onClick={openFirst}
            >
              Purchase Plan
            </Button>
          </Stack>
        </Box>
      </Flex>
      <Modal blockScrollOnMount={false} isOpen={open} onClose={onClose}>
        <ModalOverlay />
        <ModalContent>
          <ModalHeader w="70%">{planType}</ModalHeader>
          <ModalCloseButton onClick={closeModal} />
          <ModalBody>
            <FormControl>
              <FormLabel>Full name</FormLabel>
              <Input placeholder="name" />
            </FormControl>
            <FormControl mt={4}>
              <FormLabel>Email</FormLabel>
              <Input placeholder="danjoe@gmail.com" />
            </FormControl>
            <FormControl mt={4}>
              <FormLabel>Phone</FormLabel>
              <Input placeholder="+971, (4), 123 4567" />
            </FormControl>
            <FormControl mt={4}>
              <FormLabel>Address</FormLabel>
              <Input placeholder="country" />
              <Input placeholder="state" my={4} />
              <Input placeholder="residential address" />
            </FormControl>
          </ModalBody>
          <ModalFooter justifyContent="center">
            <Button colorScheme="blue" w="70%" onClick={onClose}>
              Purchase
            </Button>
          </ModalFooter>
        </ModalContent>
      </Modal>
    </div>
  );
}
